services:
  app:
    container_name: my_web_page
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    restart: unless-stopped
    networks:
      - web
  
  diabetes-progression-predictor:
    image: ghcr.io/tony-nyagah/diabetes-progression-predictor:latest
    container_name: diabetes_progression_predictor
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - web

  caddy:
    image: caddy:latest
    container_name: my_web_page_caddy
    depends_on:
      - app
      - diabetes-progression-predictor
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:

networks:
  web: